# Kraken 2: Taxnomic Sequence Classification System
# Kraken 2 is the newest version of Kraken, ataxnomic classficiation system using exact k-mer matches to achieve high accuracy and fast classification speeds.

# Bracken (Bayesian Reestimation of Abundance with KrakEN) 
Braken is a highly accurate statistical method that computes the abudance of species in DNA sequence from a metagneomics sample. 
# HUMAnN 3.0
The next iteration of HUMAnN, the HMP Unified Metabolic Analysis Network. HUMAnN is a method for efficiently and accrately profiling the abundance of microbial metabolic pathways and other molecular functions from metagenomic or metatranscirptomic sequencing data. 

01_data_preprocessing.R

# HAIIA Legacy 
"Hierarchical All-against-All association testing (HAIIA) is computational method to find multi-resolution association in high-dimensional, heterogeneous datasets. HAIIA is an end-to-end statistical method for Hierarchical All-against-All discovery of significant relationships among data features with high power. HAIIA is robust to data type, operating both on continuous and categorical values, and works well both on homogeneous datasets (where all measurements are of the same type, e.g., gene expression microarrays) and on heterogeneous data (containing measurements with different units or types, eg patient clinical metadata). In all of these cases, HAIIA will identify which pairs of features (genes, microbes, loci, etc.) share statistically signific ant information, without getting tripped up by high-dimensionality."

```{r}
```

# MMUPHin
MMUPHin is a Bioconductor package implementing meta-analysis methods for microbial comunity profiles. It has interfaces for: a) covariate-controlled batch and study effect adjustment, b) meta-analytic differential abundnace testing, and meta-analytic discovery of c) discrete (cluster-based) or d) continuous unsupervised population structure. 

Overall, MMUPHin enables the normalization and combination of multiple microbial community studies. It can then help in identifying microbes, genes, or pathways that are differential with responect to combined phenotypes. Finally, it can find clusters or gradients of smaple types that reproduce consistently among studies. 

# kebabs
The package provides functionality for kernel-based analysis of DNA, RNA, and amino acid sequences via SVM-based methods. As core functionality, kebabs implements following sequence kernels: spectrum kernel, mismatch, kernel, gappy pair kernel, and motif kernel. Apart from an efficient implementation of standard position-independent functionality, the kernels are extended in a novel way to take the position of patterns into account for the similarity measure. As support for choosing hyperparameters, the package provides cross validation - including grouped cross validation, grid search and model selection functions. For easier biological interpretation of the results, the package computes feature weights for all SVMs and prediction profiles which show the contribution of individual sequence positions to the prediction result and indicate the relevance of sequence sections for the learning result and the underlying biological functions. 

## GT-Pro approach for human stool metagenomics SNP discovery using Unified Human Gastrointesitnal Genomes (UHGG) a collection of 286,997 microbial genomes. 

## MUMmer for each speices, call SNPs by laigning each conspecific genome to the representative genome (Genome variation in gut microbial species)

# PLINK and UCLUST (SNP LD blocks)

# Extraction of sck-mers

# Selection of species-specific sck-mers

# Phylogentic resolution analysis with 16S rRNA sequences and SNPs
# fetchMG - extract 40 MGs from genomes and metagenomes in an easy and acruate manner 









